"""add review model

Revision ID: 63a973d9beb0
Revises: 89c93a3ab25e
Create Date: 2025-03-10 22:29:15.613731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a973d9beb0'
down_revision = '89c93a3ab25e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
